import {Character} from "./character";
import {CrewMember} from "./crew-member";
import {Review} from "./review";

export interface EntertainmentAllDTO {
  review:Review;
  mbid: string;
  name: string;
  artist: string;
  image: string;
  url: string;
  id: string;
  title: string;
  authors: string[];
  categories: string[];
  description: string;
  pageCount: number;
  cover_url: string;
  language: string;
  publishedDate: string;
  webReaderLink: string;
  favorite_count: number;
  releaseDate: string;
  platforms: string[];
  franchises: string[];
  genres: string[];
  developers: string[];
  publishers: string[];
  similar_games: string[];
  screenshots: string[];
  original_url: string;
  icon_url: string;
  screen_large_url: string;
  deck: string;
  characters: Character[];
  adult: boolean;
  backdrop_path: string;
  original_title: string;
  overview: string;
  poster_path: string;
  release_date: string;
  imdb_url: string;
  vote_count: number;
  tagline: string;
  directors: CrewMember[];
  actors: CrewMember[];
  writers: CrewMember[];
  first_air_date: string;
  last_air_date: string;
  original_language: string;
  status: string;
  producers: CrewMember[];
}
